apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 176408572701.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 176408572701.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 83eb5b2f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
